version: "3.1"
services:

  mysql:
    image: mysql:5.7
    container_name: uello-mysql
    working_dir: /application
    volumes:
      - .mysqldata:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uello
      - MYSQL_USER=geovane
      - MYSQL_PASSWORD=1234
    ports:
      - "8082:3306"

  webserver:
    image: nginx:alpine
    container_name: uello-webserver
    working_dir: /application
    volumes:
        - ./uelloapp:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: docker/php-fpm
    container_name: uello-php
    working_dir: /application
    volumes:
      - ./uelloapp:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

